name = "ai-search-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Vectorize Binding
[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "ai-search-suche"

# AI Binding
[ai]
binding = "AI"
