name = "sitemap-headers"
main = "index.js"
# Worker type (required by wrangler v1/v2)
type = "javascript"
compatibility_date = "2025-12-22"
# Cloudflare Account ID (provided by user)
account_id = "652ca9f4abc93203c1ecd059dc00d1da"
# Optional: Zone ID (used for setting routes automatically during publish)
zone_id = "0899c561e7100c5df4965d7b8b216bc9"

# Use the same route in Cloudflare dashboard or let wrangler set it during publish
routes = ["abdulkerimsesli.de/sitemap*"]

# Example route: abdulkerimsesli.de/sitemap*
