name = "sitemap-headers"
main = "index.js"
compatibility_date = "2025-12-22"
# Set your CF account id before publishing
account_id = "<CF_ACCOUNT_ID>"

# Use the same route in Cloudflare dashboard or set routes after `wrangler publish`
# Example route: abdulkerimsesli.de/sitemap*
